name: Build Android APK

on:
  push:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25
          check-latest: true

      - uses: dapetcu21/setup-defold@v3.0.2

      - name: Build and Bundle APK
        run: |
          java --enable-native-access=ALL-UNNAMED -jar $BOB --platform armv7-android resolve
          java --enable-native-access=ALL-UNNAMED -jar $BOB --platform armv7-android --archive build
          java --enable-native-access=ALL-UNNAMED -jar $BOB --platform armv7-android --variant debug --archive bundle

      - uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: "**/*.apk"
